name: CI

on:
  push:
    branches:
    - master
    - release/*
  pull_request:
    branches:
    - master
    - release/*

jobs:

  build:
    strategy:
      matrix:
        os: [macos-latest]
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
    - name: Install wasm-tools
      run: dotnet workload install wasm-tools wasm-experimental
    - name: Build
      run: dotnet build -c Release
    - name: Test
      run: dotnet test -c Release
    - name: Pack
      if: github.event_name != 'pull_request'
      run: dotnet pack --version-suffix "$GITHUB_RUN_NUMBER" -c Release -o ./artifacts/NuGet
    - name: Publish
      run: |
        dotnet nuget add source --username follesoe --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/follesoe/index.json"
        dotnet nuget push ./artifacts/NuGet/*.nupkg --skip-duplicate --no-symbols  --source "github"      